"""empty message

Revision ID: 00c85eb7ab93
Revises: 0920cafa9fc1
Create Date: 2025-10-24 12:03:18.492728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c85eb7ab93'
down_revision = '0920cafa9fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_index('idx_app_account_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.create_index('idx_app_account_id', ['account_id'], unique=False)
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
