"""empty message

Revision ID: d945c45db191
Revises: a30e134bf7ef
Create Date: 2025-06-13 10:11:30.901670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd945c45db191'
down_revision = 'a30e134bf7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mime_type', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False))
        batch_op.drop_column('mine_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mine_type', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_column('mime_type')

    # ### end Alembic commands ###
